config/routes.rb
Rails.application.routes.draw do
  resources :shipmentimports
  resources :parcels
  resources :shipments do
    post 'fedex/:id', to: 'shipments#gen_label', on: :collection, as: 'fedex'
  end
  devise_for :users
  resources :carriers
  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/carrier.rb
class Carrier < ApplicationRecord
  has_many :shipments
  validates :name, uniqueness: true

end

app/controllers/carriers_controller.rb
class CarriersController < ApplicationController
  before_action :set_carrier, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /carriers
  # GET /carriers.json
  def index
    @carriers = Carrier.order("created_at DESC").page(params[:page]).per(5)
  end

  # GET /carriers/1
  # GET /carriers/1.json
  def show
  end

  # GET /carriers/new
  def new
    @carrier = Carrier.new
  end

  # GET /carriers/1/edit
  def edit
  end

  # POST /carriers
  # POST /carriers.json
  def create
    @carrier = Carrier.new(carrier_params)

    respond_to do |format|
      if @carrier.save
        format.html { redirect_to @carrier, notice: 'Carrier was successfully created.' }
        format.json { render :show, status: :created, location: @carrier }
      else
        format.html { render :new }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carriers/1
  # PATCH/PUT /carriers/1.json
  def update
    respond_to do |format|
      if @carrier.update(carrier_params)
        format.html { redirect_to @carrier, notice: 'Carrier was successfully updated.' }
        format.json { render :show, status: :ok, location: @carrier }
      else
        format.html { render :edit }
        format.json { render json: @carrier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carriers/1
  # DELETE /carriers/1.json
  def destroy
    @carrier.destroy
    respond_to do |format|
      format.html { redirect_to carriers_url, notice: 'Carrier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_carrier
      @carrier = Carrier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def carrier_params
      params.require(:carrier).permit(:name, :description)
    end
end

app/views/carriers/_form.html.erb
<%= form_with(model: carrier, local: true) do |form| %>
  <% if carrier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(carrier.errors.count, "error") %> prohibited this carrier from being saved:</h2>

      <ul>
        <% carrier.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carriers/edit.html.erb
<h1>Editing Carrier</h1>

<%= render 'form', carrier: @carrier %>

<%= link_to 'Show', @carrier %> |
<%= link_to 'Back', carriers_path %>

app/views/carriers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transportistas</h1>

<%= link_to 'Nuevo Trnasportista', new_carrier_path, class: 'btn btn-primary', role: 'button' %>
<br /><br />

<table class="table">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @carriers.each do |carrier| %>
      <tr>
        <td><%= carrier.name %></td>
        <td><%= carrier.description %></td>
        <td>
          <%= link_to '<i class="fas fa-glasses fa-lg"></i>'.html_safe, carrier, class: 'btn btn-secondary' %>
          <%= link_to '<i class="fas fa-edit fa-lg"></i>'.html_safe, edit_carrier_path(carrier), class: 'btn btn-success' %>
          <%= link_to '<i class="fas fa-trash fa-lg"></i>'.html_safe, carrier, method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-danger' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @carriers, theme: 'twitter-bootstrap-4' %>
<br>

app/views/carriers/new.html.erb
<h1>New Carrier</h1>

<%= render 'form', carrier: @carrier %>

<%= link_to 'Back', carriers_path %>

app/views/carriers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @carrier.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @carrier.description %>
</p>

<%= link_to 'Edit', edit_carrier_path(@carrier) %> |
<%= link_to 'Back', carriers_path %>