config/routes.rb
Rails.application.routes.draw do
  resources :shipmentimports
  resources :parcels
  resources :shipments do
    post 'fedex/:id', to: 'shipments#gen_label', on: :collection, as: 'fedex'
  end
  devise_for :users
  resources :carriers
  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/parcel.rb
class Parcel < ApplicationRecord
  belongs_to :shipment
  validates :length, :width, :height, :weight, :distance_unit, :mass_unit,   presence: true
  before_save :volumetric
  before_update :volumetric

  def volumetric
    original_volume = self.length.to_f * self.height.to_f * self.width.to_f

    self.volumenweight = 0.5 * ((original_volume / 5000).ceil / 0.5 )
  end
end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
  before_action :set_parcel, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /parcels
  # GET /parcels.json
  def index
    @parcels = Parcel.all
  end

  # GET /parcels/1
  # GET /parcels/1.json
  def show
  end

  # GET /parcels/new
  def new
    @parcel = Parcel.new
  end

  # GET /parcels/1/edit
  def edit
  end

  # POST /parcels
  # POST /parcels.json
  def create
    @parcel = Parcel.new(parcel_params)

    respond_to do |format|
      if @parcel.save
        format.html { redirect_to @parcel, notice: 'Parcel was successfully created.' }
        format.json { render :show, status: :created, location: @parcel }
      else
        format.html { render :new }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parcels/1
  # PATCH/PUT /parcels/1.json
  def update
    respond_to do |format|
      if @parcel.update(parcel_params)
        format.html { redirect_to @parcel, notice: 'Parcel was successfully updated.' }
        format.json { render :show, status: :ok, location: @parcel }
      else
        format.html { render :edit }
        format.json { render json: @parcel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parcels/1
  # DELETE /parcels/1.json
  def destroy
    @parcel.destroy
    respond_to do |format|
      format.html { redirect_to parcels_url, notice: 'Parcel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parcel
      @parcel = Parcel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parcel_params
      params.require(:parcel).permit(:shipments_id, :length, :width, :height, :weight, :distance_unit, :mass_unit)
    end
end

app/views/parcels/_form.html.erb
<%= form_with(model: parcel, local: true) do |form| %>
  <% if parcel.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(parcel.errors.count, "error") %> prohibited this parcel from being saved:</h2>

      <ul>
        <% parcel.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shipments_id %>
    <%= form.text_field :shipments_id %>
  </div>

  <div class="field">
    <%= form.label :length %>
    <%= form.number_field :length %>
  </div>

  <div class="field">
    <%= form.label :width %>
    <%= form.number_field :width %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.number_field :height %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :distance_unit %>
    <%= form.text_field :distance_unit %>
  </div>

  <div class="field">
    <%= form.label :mass_unit %>
    <%= form.text_field :mass_unit %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parcels/edit.html.erb
<h1>Editing Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Show', @parcel %> |
<%= link_to 'Back', parcels_path %>

app/views/parcels/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parcels</h1>

<table>
  <thead>
    <tr>
      <th>Shipments</th>
      <th>Length</th>
      <th>Width</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Distance unit</th>
      <th>Mass unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parcels.each do |parcel| %>
      <tr>
        <td><%= parcel.shipments_id %></td>
        <td><%= parcel.length %></td>
        <td><%= parcel.width %></td>
        <td><%= parcel.height %></td>
        <td><%= parcel.weight %></td>
        <td><%= parcel.distance_unit %></td>
        <td><%= parcel.mass_unit %></td>
        <td><%= link_to 'Show', parcel %></td>
        <td><%= link_to 'Edit', edit_parcel_path(parcel) %></td>
        <td><%= link_to 'Destroy', parcel, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parcel', new_parcel_path %>

app/views/parcels/new.html.erb
<h1>New Parcel</h1>

<%= render 'form', parcel: @parcel %>

<%= link_to 'Back', parcels_path %>

app/views/parcels/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipments:</strong>
  <%= @parcel.shipments_id %>
</p>

<p>
  <strong>Length:</strong>
  <%= @parcel.length %>
</p>

<p>
  <strong>Width:</strong>
  <%= @parcel.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @parcel.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @parcel.weight %>
</p>

<p>
  <strong>Distance unit:</strong>
  <%= @parcel.distance_unit %>
</p>

<p>
  <strong>Mass unit:</strong>
  <%= @parcel.mass_unit %>
</p>

<%= link_to 'Edit', edit_parcel_path(@parcel) %> |
<%= link_to 'Back', parcels_path %>