config/routes.rb
Rails.application.routes.draw do
  resources :shipmentimports
  resources :parcels
  resources :shipments do
    post 'fedex/:id', to: 'shipments#gen_label', on: :collection, as: 'fedex'
  end
  devise_for :users
  resources :carriers
  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shipment.rb
class Shipment < ApplicationRecord
  belongs_to :user
  belongs_to :carrier
  has_one :parcel, dependent: :destroy

  validates :tracking_number, uniqueness: true
  validates :carrier_id, :user_id, presence: true


  accepts_nested_attributes_for :parcel, allow_destroy: true, reject_if: proc { |attr| attr['length'].blank? }



  def self.gen_tracking_number
    loop do
      tracking_number = SecureRandom.random_number(999999999999999)
      break tracking_number unless Shipment.where(tracking_number: tracking_number).exists?
    end
  end


end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  before_action :set_shipment, only: [:show, :edit, :update, :destroy, :gen_label]
  before_action :set_catalog, only: [:new, :edit, :update, :create]
  before_action :authenticate_user!
  # GET /shipments
  # GET /shipments.json
  def index
    @shipments = Shipment.order("created_at DESC").page(params[:page]).per(5)
  end

  # GET /shipments/1
  # GET /shipments/1.json
  def show
  end

  # GET /shipments/new
  def new
    @shipment = Shipment.new
    @shipment.tracking_number = Shipment.gen_tracking_number
    @shipment.build_parcel

  end

  # GET /shipments/1/edit
  def edit
    if !@shipment.parcel
      @shipment.build_parcel

    end
  end

  # POST /shipments
  # POST /shipments.json
  def create
    @shipment = current_user.shipments.build(shipment_params)
    respond_to do |format|
      if @shipment.save
        format.html { redirect_to @shipment, notice: 'Shipment was successfully created.' }
        format.json { render :show, status: :created, location: @shipment }
      else
        format.html { render :new }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  def gen_label
    fedex = Fedex::Shipment.new(:key => ENV['SRENVIO_FEDEX_KEY'],
                                :password => ENV['SRENVIO_FEDEX_PASSWORD'],
                                :account_number => ENV['SRENVIO_FEDEX_ACCOUNT'],
                                :meter => ENV['SRENVIO_FEDEX_MASTER'],
                                :mode => ENV['SRENVIO_FEDEX_MODE'])


    shipper = { :name => "Sender",
                :company => "Company",
                :phone_number => "555-555-5555",
                :address => "Main Street",
                :city => "Harrison",
                :state => "AR",
                :postal_code => "72601",
                :country_code => "US" }

    recipient = { :name => "Recipient",
                  :company => "Company",
                  :phone_number => "555-555-5555",
                  :address => "Main Street",
                  :city => "Franklin Park",
                  :state => "IL",
                  :postal_code => "60131",
                  :country_code => "US",
                  :residential => "false" }

    packages = [{
                :weight => {:units => @shipment.parcel.mass_unit, :value =>@shipment.parcel.weight.to_f.ceil},
                :dimensions => {
                    :length =>@shipment.parcel.length.to_i, :width =>@shipment.parcel.width.to_i,
                    :height =>@shipment.parcel.height.to_i, :units =>@shipment.parcel.distance_unit
                }}]

    shipping_options = {
        :packaging_type => "YOUR_PACKAGING",
        :drop_off_type => "REGULAR_PICKUP"
    }


    rate = fedex.rate(:shipper=>shipper,
                      :recipient => recipient,
                      :packages => packages,
                      :service_type => "FEDEX_GROUND",
                      :shipping_options => shipping_options)

    # raise rate.inspect

    @shipment.total_base_charge = rate[0].total_base_charge.to_f
    @shipment.total_surcharges = rate[0].total_surcharges.to_f
    @shipment.total_net_charge = rate[0].total_net_charge.to_f
    @shipment.save
    redirect_to shipments_path, notice: 'Fedex generado'

  end

  # PATCH/PUT /shipments/1
  # PATCH/PUT /shipments/1.json
  def update
    @carriers = Carrier.all

    respond_to do |format|
      if @shipment.update(shipment_params)
        format.html { redirect_to @shipment, notice: 'Shipment was successfully updated.' }
        format.json { render :show, status: :ok, location: @shipment }
      else
        format.html { render :edit }
        format.json { render json: @shipment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.json
  def destroy
    @shipment.destroy
    respond_to do |format|
      format.html { redirect_to shipments_url, notice: 'Shipment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    def set_catalog
      @carriers = Carrier.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shipment_params
      params.require(:shipment).permit(:carrier_id, :tracking_number, :user_id,
       parcel_attributes: [:_destroy, :id, :shipment_id, :length, :width, :height, :weight, :distance_unit, :mass_unit, :total_base_charge, :total_net_freight, :total_net_charge]

      )
    end
end

app/views/shipments/_form.html.erb
<%= form_with(model: shipment, local: true) do |form| %>
  <% if shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
        <% shipment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tracking_number, 'Número de guia' %>
    <input type="text" value="<%= @shipment.tracking_number %>" readonly class="form-control col-md-2">
    <%= form.hidden_field :tracking_number %>
  </div>


  <div>
    <label>Transportista</label> <br />
    <%= form.collection_select :carrier_id, @carriers.order(:name),:id,:name,{ include_blank: true}, { class: 'form-control col-md-2', required: true} %>

  </div>

  <div>

    <%= form.fields_for :parcel do |parcel_form| %>
      <div class="field">
        <%= parcel_form.label :length, 'Longitud' %>
        <%= parcel_form.number_field :length, class: 'form-control col-md-2', step: :any, :required => true %>
      </div>

      <div class="field">
        <%= parcel_form.label :width, 'Ancho' %>
        <%= parcel_form.number_field :width, class: 'form-control col-md-2', step: :any, :required => true %>
      </div>

      <div class="field">
        <%= parcel_form.label :height, 'Alto' %>
        <%= parcel_form.number_field :height, class: 'form-control col-md-2', step: :any, :required => true %>
      </div>

      <div class="field">
        <%= parcel_form.label :weight, 'Peso' %>
        <%= parcel_form.number_field :weight, class: 'form-control col-md-2', step: :any, :required => true %>
      </div>

      <div class="field">
        <%= parcel_form.label :distance_unit, 'Unidad de distancia' %>
        <input type="text" value="CM" readonly class="form-control col-md-2">
        <%= parcel_form.hidden_field :distance_unit, class: 'form-control col-md-2', value: 'CM' %>
      </div>

      <div class="field">
        <%= parcel_form.label :mass_unit, 'Unidad de masa' %>
        <input type="text" value="KG" readonly class="form-control col-md-2">
        <%= parcel_form.hidden_field :mass_unit, class: 'form-control col-md-2', value: 'KG' %>
      </div>
    <% end %>

  </div>

  <div class="">
    <br />
    <br />
    <%= link_to 'Regresar', shipments_path, class: 'btn btn-secondary' %> <%= form.submit 'Generar envio', class: 'btn btn-primary' %>

  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editar envío</h1>

<%= render 'form', shipment: @shipment %>

app/views/shipments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Envios</h1>

<%= link_to 'Nuevo Envio', new_shipment_path, class: 'btn btn-primary', role: 'button' %> <br />
<br /><br />

<table class="table">
  <thead>
    <tr>
      <th>Número de rastreo</th>
      <th>Transportista</th>
      <th>Peso Total</th>
      <th>Fedex base</th>
      <th>Peso extra</th>
      <th>Peso Total Fedex</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @shipments.each do |shipment| %>
      <tr>
        <td><%= shipment.tracking_number %></td>
        <td><%= shipment.carrier.name %></td>
        <td><%= shipment.parcel.volumenweight %></td>
        <td><%= shipment.total_base_charge %></td>
        <td><%= shipment.total_surcharges %></td>
        <td><%= shipment.total_net_charge %></td>
        <td><%= shipment.created_at.strftime('%d-%m-%Y') %></td>
        <td><%= shipment.created_at.strftime('%H:%M') %></td>
        <td>
          <%= link_to '<i class="fas fa-glasses fa-lg"></i>'.html_safe, shipment, class: 'btn btn-secondary' %>
          <%= link_to '<i class="fab fa-fedex fa-lg "></i>'.html_safe, fedex_shipments_path(shipment), class: 'btn btn-info', method: :post unless shipment.total_base_charge != 0.0 %>
          <%= link_to '<i class="fas fa-edit fa-lg"></i>'.html_safe, edit_shipment_path(shipment), class: 'btn btn-success' unless shipment.total_base_charge != 0.0 %>
          <%= link_to '<i class="fas fa-trash fa-lg"></i>'.html_safe, shipment, method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-danger' unless shipment.total_base_charge != 0.0 %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @shipments, theme: 'twitter-bootstrap-4' %>
<br>

app/views/shipments/new.html.erb
<h1>Nuevo envío</h1>

<%= render 'form', shipment: @shipment %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card text-center">
  <div class="card-header">
    Envío generado por: <%= @shipment.user.email %>
  </div>
  <div class="card-body">
    <h5 class="card-title">Guia  <b><%= @shipment.tracking_number %></b></h5>
    <p class="card-text">Transportista: <b><%= @shipment.carrier.name %></b> </p>

    <div class="row col-12 justify-content-md-center">

    <ul class="list-group">
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Longitud:
        <span class="badge badge-primary badge-pill"><%= @shipment.parcel.length %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Ancho:
        <span class="badge badge-primary badge-pill"><%= @shipment.parcel.width %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Alto:
        <span class="badge badge-primary badge-pill"><%= @shipment.parcel.height %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Peso:
        <span class="badge badge-primary badge-pill"><%= @shipment.parcel.weight %></span>
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Peso Total:
        <span class="badge badge-primary badge-pill"><%= @shipment.parcel.volumenweight %></span>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        Fedex base:
        <span class="badge badge-primary badge-pill"><%= @shipment.total_base_charge %></span>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        Peso extra:
        <span class="badge badge-primary badge-pill"><%= @shipment.total_surcharges %></span>
      </li>

      <li class="list-group-item d-flex justify-content-between align-items-center">
        Peso Total Fedex:
        <span class="badge badge-primary badge-pill"><%= @shipment.total_net_charge %></span>
      </li>
    </ul>
    </div>

    <br />
    <br />
    <%= link_to 'Regresar', shipments_path, class: 'btn btn-secondary' %>  <%= link_to '<i class="fas fa-trash fa-lg"></i>'.html_safe, @shipment, method: :delete, data: { confirm: 'Estas seguro?' }, class: 'btn btn-danger' unless @shipment.total_base_charge != 0.0 %>

  </div>
  <div class="card-footer text-muted">
    Envío creado hace <%= time_ago_in_words(@shipment.created_at) %>
  </div>
</div>