config/routes.rb
Rails.application.routes.draw do
  resources :shipmentimports
  resources :parcels
  resources :shipments do
    post 'fedex/:id', to: 'shipments#gen_label', on: :collection, as: 'fedex'
  end
  devise_for :users
  resources :carriers
  root 'main#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Lab-SrEnvio</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item ">
        <%= link_to 'Inicio', root_path, class: 'nav-link'  %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item ">
          <%= link_to 'Envios', shipments_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item ">
          <%= link_to 'Transportistas', carriers_path, class: 'nav-link'  %>
        </li>

      <% end %>


    </ul>

    <ul class="nav navbar-nav ml-auto">
      <% if user_signed_in? %>
        <li class="nav-item ">
          <%= link_to 'Importar envios', shipmentimports_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item dropleft">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Cuenta
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">

            <div class="dropdown-divider"></div>
            <%= link_to 'Cerrar Sesion', destroy_user_session_path, method: :delete, class: 'dropdown-item'  %>
          </div>
        </li>
      <% else %>
        <%= link_to 'Iniciar Sesion', new_user_session_path, class: 'nav-link'  %>
      <% end %>

    </ul>


  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LabSrenvio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



  <div class="container-fluid">
    <%= render './layouts/navbar' %>

    <%= yield %>
  </div>


  </body>
</html>